### ISSUE TITLE
make install, tries to install python module in system wide python module folder

### ISSUE THREAD

**Issue by HugoStrand** [SpM-lab/irlib#1]
Dear Hiroshi,

Thank you for putting this together! It will make it easier for people to play with your basis functions. 👍  

I had a small issue when trying to do `make install`. Usually when one provides an install prefix path to `cmake` using `-DCMAKE_INSTALL_PREFIX=...` the `make install` command only tries to install files in that folder (and subfolders). This makes it possible to do a user installation even on systems where you do not have root access (like HPC clusters).

However, by default `irlib` tries to install the python module and bindings into the system wide python module folder. I would suggest to change the default behaviour so that `make install` only installs files under the install prefix folder.

Cheers,
Hugo

**Comment by shinaoka** [comment]
Thank you for the suggestion. The default behavior has been changed!
