### ISSUE TITLE
Failure of some tests

### ISSUE THREAD

**Issue by dombrno** [SpM-lab/irlib#2]
Dear Hiroshi, Junya, thank you for providing this tool to the community. I have tried to install/compile/run the code, and unfortunately some tests have failed. The log file with details is attached, I am not sure about that python import error with basis_f, another error probably has to do with a too small tolerance, I have not looked at the other ones in detail yet.
[LastTest.log](https://github.com/SpM-lab/irlib/files/2057822/LastTest.log)

**Comment by shinaoka** [comment]
Thank you for the feedback.
I will have a look.

BTW, I forward you to a new tool "irbasis".
https://pypi.org/project/irbasis/

That library contains precomputed data of basis functions for selected values of Lambda (computed by irlib) and some tools for interpolating basis functions and computation of transformation matrix to Matsubara frequencies.
If you want, we can provide sample codes for irbasis.

"irbasis" is going to be advertised, while "irlib" stays a developer tool for us.
We are implementing a C++ version of "irbasis", which will be public soon.

The repository of irbasis is still private but will be public at some point.

**Comment by dombrno** [comment]
Thank you very much, it is so nice to be able to access it in a packaged way like this. Installation via pip ran with no issue.

**Comment by shinaoka** [comment]
Thank you!
All the issues have been fixed in the latest commit!
